### ISSUE TITLE
can we stop putting installer binaries in the repos directly? 

### ISSUE THREAD

**Issue by divinity76** [blackdtools/Blackd-Proxy-CLASSIC#85]
keep doing this makes the repo very big when you clone the entire history over several years; since git forgets nothing, it remembers every single version of the installer, and makes the repository history much bigger. thus i suggest we stop putting the installer binaries in the repo itself, and make "github releases" instead, which are NOT stored in the git history (it is stored on github.com servers only), see  how to do that here - https://help.github.com/articles/creating-releases/

just noticed that today, after not playing tibia for quite a while, decided to try again; cloned blackd proxy sources, and it took a while to download, i bet most of it is those installers.

**Comment by blackdtools** [comment]
Sorry, I didn’t know GitHub forces to download all old installers.

I was uploading installers because it saves some bandwidth at my server.

Anyways I only need to do a direct link to the latest installer file from my download section). It is possible to do keep doing that with the “releases”? 
- Daniel Peña Vázquez (  http://www.blackdtools.com www.blackdtools.com ) 

LEGAL NOTICE - ABOUT CONFIDENTIAL INFORMATION 

This message and its contents may contain confidential information and its non-authorised use is prohibited by law. If you are not the intended recipient of this email or do not wish to receive marketing information, please advise the sender of the fact using the same, or other, means and delete this message and its contents from your system without copying, forwarding or revealing the contents of the message to any other person. Any information, opinion,conclusion, recommendation, etc. contained in this message and which is unrelated to the business activity of DANIEL PEÑA VAZQUEZ and/or issued by unauthorised personnel, shall be considered unapproved by DANIEL PEÑA VAZQUEZ. DANIEL PEÑA VAZQUEZ implements control measures to ensure, as far as possible, the security and reliability of all its electronic correspondence. However, does not guarantee that emails are virus-free or that documents have not be altered and takes no responsibility in this respect. 

NOTA LEGAL - CLÁUSULA DE CONFIDENCIALIDAD 

Este mensaje y sus anexos pueden contener información confidencial, por lo que se informa de que su uso no autorizado está prohibido por la ley. Si Vd. considera que no es el destinatario pretendido por el remitente o no desea recibir información comercial, por favor póngalo en su conocimiento por esta misma vía o por cualquier otro medio elimine esta comunicación y los anexos de su sistema, sin copiar, remitir o revelar los contenidos del mismo a cualquier otra persona. Cualquier información, opinión, conclusión, recomendación, etc. contenida en el presente mensaje no relacionada con la actividad empresarial de DANIEL PEÑA VAZQUEZ y/o emitida por persona sin capacidad para ello, deberá considerarse como no proporcionada ni aprobada por DANIEL PEÑA VAZQUEZ. DANIEL PEÑA VAZQUEZ pone los medios a su alcance para garantizar la seguridad y ausencia de errores en la correspondencia electrónica, pero no puede asegurar la inexistencia de virus o la no alteración de los documentos transmitidos electrónicamente, por lo que declina cualquier responsabilidad a este respecto. 

De: divinity76 [mailto:notifications@github.com] 
Enviado el: sábado, 03 de septiembre de 2016 13:42
Para: blackdtools/Blackd-Proxy-CLASSIC
Asunto: [blackdtools/Blackd-Proxy-CLASSIC] can we stop putting installer binaries in the repos directly? (#85)

keep doing this makes the repo very big when you clone the entire history over several years; since git forgets nothing, it remembers every single version of the installer, and makes the repository history much bigger. thus i suggest we stop putting the installer binaries in the repo itself, and make "github releases" instead, see how to do that here - https://help.github.com/articles/creating-releases/

just noticed that today, after not playing tibia for quite a while, decided to try again; cloned blackd proxy sources, and it took a while to download, i bet most of it is those installers.

**Comment by divinity76** [comment]
Yes, you can do that. here is a test "release" i just did. it was also very easy to make a release :) - release direct url: https://github.com/divinity76/Blackd-Proxy-NG/releases/download/testrelease/kitty.exe

**Comment by blackdtools** [comment]
ok. I will start working with releases today
