### ISSUE TITLE
red square for 7.7

### ISSUE THREAD

**Issue by newacc123** [blackdtools/Blackd-Proxy-CLASSIC#86]
Red square does not work for 7.7. I think we are missing the memory address in config file.

**Comment by divinity76** [comment]
this also affects the bot's ability to NOT spam the attack packets. related: https://github.com/blackdtools/Blackd-Proxy-CLASSIC/issues/57

i believe this bug is present in every version from 7.7 to 8.61 , per https://github.com/blackdtools/Blackd-Proxy-CLASSIC/issues/57#issuecomment-186111089

should be fixed. could someone make an easy tutorial on how to find the red square address?

(iirc, i think i could find it by using Cheat Engine, turning off ASLR per http://stackoverflow.com/a/9561263 , finding the battle list in memory, then looking at id of the creatures (which is the first 4 bytes of each creature), then then selecting a target in-client, and search for whatever memory address has the first 4 bytes of the creature selected, then just switching the targets a couple of times and re-searching with cheat engine, soon enough i have the red square address. and i can confirm by manually altering the target with cheat engine to another creature id.)

but i don't have tibia 7.7 (nor ANY version of tibia) nor blackd proxy installed atm, so i can't really make a tutorial on it atm.
- and there may be an easier way. i recall BlackD told me something about that... nearby hex values that hardly ever change between versions or something, iirc?

**Comment by newacc123** [comment]
I tried to search the memory addresses that change when I attack a creature or hover over the battle list  using cheat engine and these are the addresses:

0056C81C
04EC011C
04EC0120
04EC0440
04EC076C

How would I convert this to &H format to test one by one in BlackD config file and check if they work?

**Comment by blackdtools** [comment]
just use cheat engine,
you should obtain an adress like this: tibia.exe + XXXXXXXX
Finally just replace tibia.exe to 400000 and the resulting sum is the address used by blackd proxy.

**Comment by newacc123** [comment]
OK. I updated config.ini for 7.70 with RedSquare=&H56C81C and it seems to work! Thanks!

**Comment by divinity76** [comment]
good job. @newacc123 do you want to make a pull request? should be added to offical blackd proxy distribution :+1:  

(PS, if ASLR is disabled, tibia.exe should already be 400000 in cheat engine)
